name: 'AudioHead'
freeze: False
from_scratch: False
embed_dim: ${model.image.embed_dim}
meme_path: ''
meme_name: ''
time_first: True
resolution: 
- ${running.max_audio_len}
- ${running.num_mel_bins}
width: 64 
layers:
- 4
- 6
- 10
- 6
