name: 'CLIPAudioHead'
freeze: False #True #
from_scratch: False #True #
width: ${model.image.width} 
embed_dim: ${model.image.embed_dim}
resolution: 
- ${running.max_audio_len}
- ${running.num_mel_bins} 
ctx_len: ${model.text.ctx_len}
encoder:
    name: ResNetBackbone
    layers: ${model.image.encoder.layers}
pre_encoder:
    name: ResNetPreEncoder
    in_channels: 3 
post_encoder:
    name: ResNetPostEncoder
misc:
    name: CLIPMisc
pre_encoder_addon:
    name: AddonEncoder
post_encoder_addon:
    name: AddonEncoder
