name: 'AudioHead'
freeze: False
from_scratch: False
embed_dim: ${model.image.embed_dim}
resolution: 
- ${running.max_audio_len}
- ${running.num_mel_bins} 
patch_size: ${model.image.patch_size}
width: 768 
stride: [16, 16] 
layers: 12
