name: 'ImagineAndClassifyLossHead'
lambd_ce: 1. 
layers: 
- ${model.image.embed_dim}
bias: False
ce:
    name: 'CELossHead'
    alive: True
    scaling: True
    scale_max: null
bce:
    name: 'BCELossHead'
    alive: True
    embed_dim: ${model.audio.embed_dim}
    width: ${model.audio.width}
    layers: []
    scaling: True 
    bias: False
