clip_model_root: "/net/nfs2.mosaic/yann/model/clip" 
clip_model_name: "ViT-B32"
data_root: "/home/yanpengz/data/audioset" 
prompt: "the sound of"
label_map: "ontology,eval_segments" 
data_name: 'npz_train_toy' #'src_train_toy' #
eval_name: 'npz_eval_toy' #'src_eval_toy' #
test_name: 'npz_eval_toy' #'src_eval_toy' #
eval_samples: 250 
test_samples: 5000
peep_rate: 1 
save_rate: 3 
batch_size: 64 
epochs: 1000 
save_epoch: False
clf: True
imagine: False
# vision backbone
resolution: ${model.image.resolution}
# audio backbone
max_audio_len: ${running.audio.max_len}
num_mel_bins: ${running.audio.num_mel_bins} 
