clip_model_root: "/net/nfs2.mosaic/yann/model/clip" 
clip_model_name: "ViT-B32"
nsample_per_vid: 10 # # samples per VoxCeleb id
data_root: "/home/yanpengz/data/esc50" 
visual_prompt: False
prompt: "the sound of " #"label_map" for ESC50 and US8K
text: "the video of<|MASK|>"
encoder_type: "audio" 
label_map: "" # for AudioSet 
data_name: 'esc50' 
zero_shot: True 
eval_name: '' 
test_name: '' 
eval_samples: 5000
test_samples: 5000
peep_rate: 16 
save_rate: 32 
batch_size: 50 
epochs: 32
save_epoch: False
