clip_model_root: "/net/nfs2.mosaic/yann/model/clip" 
clip_model_name: "ViT-B32"
data_root: "/home/yanpengz/data/audioset" 
data_name: 'npz_train_toy'
eval_name: 'npz_eval_toy'
test_name: 'npz_eval_toy'
eval_samples: 250 
test_samples: 5000
max_audio_len: 1000
peep_rate: 1 
save_rate: 3 
batch_size: 64 
epochs: 1000 
