clip_model_root: "/net/nfs2.mosaic/yann/model/clip" 
clip_model_name: "ViT-B32"
data_root: "/home/yanpengz/data/audioset" #"gs://yannaudioset"
data_name: 'src_train_toy'
eval_name: 'src_eval_toy'
test_name: 'src_eval_toy'
train_samples: 1.
eval_samples: 250 
test_samples: 5000
peep_rate: 1 
save_rate: 3 
batch_size: 64 
epochs: 1000 
save_epoch: False
frame_key: "frame"
frame_emb: null
embed_dim: ${model.image.embed_dim}
# vision backbone
resolution: ${model.image.resolution}
# audio backbone
max_audio_len: ${running.audio.max_len}
num_mel_bins: ${running.audio.num_mel_bins} 
