clip_model_root: "/net/nfs2.mosaic/yann/model/clip" 
clip_model_name: "ViT-B32"
data_root: "/home/yanpengz/data/audioset/tfrecord"
data_name: 'train_balanced'
eval_name: 'eval'
max_audio_len: 1000
batch_size: 64 
epochs: 100
peep_rate: 45 
save_rate: 200 
