clip_model_root: "/net/nfs2.mosaic/yann/model/clip" 
clip_model_name: "ViT-B32"
data_root: "/home/yanpengz/data/us8k/UrbanSound8K"
label_map: "the sound of " #"label_map"
data_name: 'UrbanSound8K' 
eval_name: '' 
test_name: '' 
eval_samples: 5000
test_samples: 5000
peep_rate: 50 
save_rate: 1e9 
batch_size: 50 
epochs: 32
save_epoch: True 
# vision backbone
resolution: ${model.image.resolution}
# audio backbone
max_audio_len: ${running.audio.max_len}
num_mel_bins: ${running.audio.num_mel_bins}
