alias_root: "/net/nfs2.mosaic/yann/model/cvap" 
model_root: "/net/nfs2.mosaic/yann/model/cvap" 
model_name: "test"
model_file: "00000204.pth"
blockprint: False
monitor: DPMonitor
worker: CVAPDP
verbose: False
seed: 1213
eval: True 
rank: -1
mode: "ddp"
num_proc: 0 # always 0 in ddp mode 
num_gpus: 4 
port: 22829
dist_url: "tcp://localhost:${port}"
