# kaldi
max_len: 1000 # seq len
norms: [] 
eval_norms: False
normalized: False
dither: 0.0
tile_audio: False
frame_shift: 10
htk_compat: True
use_energy: False
window_type: hanning
num_mel_bins: 128
zero_mean_wf: True
# transform of audios 
transform_audio: False
audio_transforms: []
# transform of fbanks 
transform_fbank: True 
fbank_transforms:
- [FrequencyMasking, [32]]
- [TimeMasking, [200]]
