# kaldi
max_len: 1000 # seq len 
norms: [] 
eval_norms: False
normalized: False
frame_length: 25
frame_shift: 10
window_type: hamming
num_mel_bins: 128
low_freq: 0.0
high_freq: 8000
use_log_fbank: True
zero_mean_wf: False
# transform of audios 
transform_audio: False
audio_transforms:
- [RandomFlip, {p: 0.5}]
- [RandomScale, {scale: 1.5, keep_len: True}]
- [RandomNoise, {snr_min_db: 10.0, snr_max_db: 120.0, p: 0.25}]
# transform of fbanks 
transform_fbank: True 
fbank_transforms:
- [SimpleRandomNoise, []]
- [FrequencyMasking, [25]]
- [TimeMasking, [100]]
